from .cv import router as cv_router
from .trajectory import router as trajectory_router
from .creators import router as creators_router
from .candidates import router as candidates_router
from .bookings import router as bookings_router
from .assessment import router as assessment_router
from .recruiter import router as recruiter_router
from .analytics import router as analytics_router
from .jobs import router as jobs_router
